# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        exclude: |
          (?x)^(
              ^api/migrations/.*|
          )$

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        args: [
          --max-line-length, "120",
          --ignore, "F403"
        ]
        exclude: |
          (?x)^(
              ^api/migrations/.*|
              api/models/__init__.py|
              config/settings/dev.py|
              config/settings/prd.py|
              manage.py
          )$
        additional_dependencies: [
          darglint,
          flake8,
          flake8-bandit,
          flake8-bugbear,
          flake8-builtins,
          flake8-comprehensions,
          flake8-eradicate,
          flake8-isort,
          flake8-pytest-style,
          flakehell,
          pep8-naming
        ]
