runs:
  using: "Composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9.13
        architecture: x64

    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        ignore: F403
        max-line-length: 120
        exclude: ^api/migrations/.*,api/models/__init__.py,config/settings/dev.py,config/settings/prd.py,manage.py
        plugins: darglint flake8==3.9.0 flake8-bandit flake8-bugbear flake8-builtins flake8-comprehensions flake8-eradicate flake8-isort flake8-pytest-style flakehell==0.9.0 pep8-naming
