name: Push

on:
  pull_request:
    branches:
      - develop
      - main
    types:
      - opened
      - edited
      - reopened

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: ./.github/actions/initialize

      - name: Lint
        uses: ./.github/actions/lint
