name: Push

on:
  push:
    branches-ignore:    
        - develop
        - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Lint
        uses: ./.github/actions/lint
