name: Push

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
  steps:
    - name: Initialize
      uses: ./.github/workflows/actions/initialize

    - name: Lint
      uses: ./.github/workflows/actions/lint
