name: Push

on: push

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Initialize
        uses: ./.github/workflows/actions/initialize

      - name: Lint
        uses: ./.github/workflows/actions/lint
